baseURL = "https://blog.balajisivaraman.com/"
languageCode = "en-us"
title = "Balaji Sivaraman"

# Enable Chroma Syntax Highlighting
pygmentsOptions = "linenos=true"
pygmentsStyle = "github"
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
preserveTaxonomyNames = true
disableKinds = ["sitemap"]

[permalinks]
post = "/:slug"

[params]
author = "Balaji Sivaraman"
bio = "Software Developer, Lifelong Learner, Writer, Speaker, Teacher"
description = "Balaji Sivaraman is a Lead Technologist who writes about software development, software architecture, and technical leadership on these pages"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = true
