baseURL = "https://www.balajisivaraman.com/"
languageCode = "en-us"
title = "Balaji Sivaraman"

# Enable Chroma Syntax Highlighting
pygmentsOptions = "linenos=true"
pygmentsStyle = "dracula"
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true

preserveTaxonomyNames = true

[permalinks]
post = "/:slug"

[params]
author = "Balaji Sivaraman"
description = "Software Developer, Lifelong Learner, Writer, Speaker, Teacher"
bio = "Hi, I'm Balaji Sivaraman, a Lead Technologist at ThoughtWorks. On these pages, you will find my thoughts on programming languages, software architecture, and technical leadership."
disqusShortname = "https-www-balajisivaraman-com"
enable_comments = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = true
