baseURL = "https://www.balajisivaraman.com/"
languageCode = "en-us"
title = "Balaji Sivaraman"

# Enable Chroma Syntax Highlighting
pygmentsOptions = "linenos=true"
pygmentsStyle = "github"
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true

preserveTaxonomyNames = true

[permalinks]
post = "/:slug"

[params]
author = "Balaji Sivaraman"
bio = "Software Developer, Lifelong Learner, Writer, Speaker, Teacher"
description = "Balaji Sivaraman is a Lead Technologist who writes about software development, software architecture, and technical leadership on these pages"
disqusShortname = "https-www-balajisivaraman-com"
enable_comments = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = true
